export type Product = {
  id: string;
  name: string;
  ageGroup: "kids" | "adults";
  category: "tops" | "bottoms" | "outerwear" | "accessories" | "footwear";
  priceUsd: number;
  sizes: string[];
  colors: string[];
  productDescription: string;
  inventory: number;
};

export const PRODUCTS: Product[] = [
  {
    id: "tee-001",
    name: "Nimbus Cotton Tee",
    ageGroup: "adults",
    category: "tops",
    priceUsd: 28,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["white", "midnight", "sage"],
    productDescription: "Soft combed cotton tee with a relaxed fit and reinforced neck.",
    inventory: 42,
  },
  {
    id: "hood-002",
    name: "Atlas Fleece Hoodie",
    ageGroup: "adults",
    category: "outerwear",
    priceUsd: 74,
    sizes: ["S", "M", "L", "XL"],
    colors: ["charcoal", "sand"],
    productDescription: "Heavyweight fleece hoodie with double-layer hood and hidden pocket.",
    inventory: 18,
  },
  {
    id: "pants-003",
    name: "Tide Tapered Chino",
    ageGroup: "adults",
    category: "bottoms",
    priceUsd: 62,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["navy", "khaki", "olive"],
    productDescription: "Tapered chino with stretch cotton and a clean, minimal finish.",
    inventory: 30,
  },
  {
    id: "jkt-004",
    name: "Summit Shell Jacket",
    ageGroup: "adults",
    category: "outerwear",
    priceUsd: 128,
    sizes: ["S", "M", "L"],
    colors: ["black", "slate"],
    productDescription: "Lightweight shell with water resistance and breathable lining.",
    inventory: 12,
  },
  {
    id: "cap-005",
    name: "Drift Canvas Cap",
    ageGroup: "kids",
    category: "accessories",
    priceUsd: 24,
    sizes: ["OS"],
    colors: ["ecru", "forest"],
    productDescription: "Structured canvas cap with an adjustable brass buckle.",
    inventory: 55,
  },
  {
    id: "sneak-006",
    name: "Flux Knit Runner",
    ageGroup: "kids",
    category: "footwear",
    priceUsd: 96,
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["graphite", "cloud"],
    productDescription: "Knit runner with cushioned midsole and grippy outsole.",
    inventory: 20,
  },
  {
    id: "tee-007",
    name: "Coastline Pocket Tee",
    ageGroup: "kids",
    category: "tops",
    priceUsd: 26,
    sizes: ["XS", "S", "M", "L"],
    colors: ["sky", "cream"],
    productDescription: "Lightweight pocket tee with breathable jersey knit fabric.",
    inventory: 48,
  },
  {
    id: "short-008",
    name: "Harbor Pull-On Shorts",
    ageGroup: "kids",
    category: "bottoms",
    priceUsd: 34,
    sizes: ["XS", "S", "M", "L"],
    colors: ["denim", "stone"],
    productDescription: "Easy pull-on shorts with elastic waistband and soft twill.",
    inventory: 36,
  },
  {
    id: "crew-009",
    name: "Ember Crew Sweatshirt",
    ageGroup: "adults",
    category: "tops",
    priceUsd: 58,
    sizes: ["S", "M", "L", "XL"],
    colors: ["ash", "copper"],
    productDescription: "Brushed fleece crew with ribbed cuffs and hem.",
    inventory: 24,
  },
  {
    id: "vest-010",
    name: "Northwind Quilted Vest",
    ageGroup: "adults",
    category: "outerwear",
    priceUsd: 92,
    sizes: ["S", "M", "L", "XL"],
    colors: ["ink", "moss"],
    productDescription: "Quilted vest with lightweight insulation and snap front.",
    inventory: 16,
  },
  {
    id: "sock-011",
    name: "Field Rib Socks",
    ageGroup: "adults",
    category: "accessories",
    priceUsd: 18,
    sizes: ["M", "L"],
    colors: ["heather", "navy", "russet"],
    productDescription: "Ribbed cotton socks with reinforced heel and toe.",
    inventory: 80,
  },
  {
    id: "belt-012",
    name: "Traverse Web Belt",
    ageGroup: "adults",
    category: "accessories",
    priceUsd: 28,
    sizes: ["OS"],
    colors: ["black", "coyote"],
    productDescription: "Durable web belt with matte metal buckle.",
    inventory: 40,
  },
  {
    id: "boot-013",
    name: "Pioneer Trail Boot",
    ageGroup: "adults",
    category: "footwear",
    priceUsd: 148,
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["espresso", "stone"],
    productDescription: "Water-resistant leather boot with rugged lug outsole.",
    inventory: 14,
  },
  {
    id: "sneak-014",
    name: "Echo Low Sneaker",
    ageGroup: "adults",
    category: "footwear",
    priceUsd: 110,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["white", "charcoal"],
    productDescription: "Low-profile sneaker with cushioned footbed and gum sole.",
    inventory: 22,
  },
  {
    id: "beanie-015",
    name: "Fjord Knit Beanie",
    ageGroup: "kids",
    category: "accessories",
    priceUsd: 20,
    sizes: ["OS"],
    colors: ["berry", "oat"],
    productDescription: "Soft knit beanie with a fold-over cuff for warmth.",
    inventory: 60,
  },
  {
    id: "jog-016",
    name: "Canyon Fleece Jogger",
    ageGroup: "kids",
    category: "bottoms",
    priceUsd: 38,
    sizes: ["XS", "S", "M", "L"],
    colors: ["charcoal", "spruce"],
    productDescription: "Cozy fleece jogger with tapered leg and ankle cuff.",
    inventory: 28,
  },
  {
    id: "polo-017",
    name: "Marina Pique Polo",
    ageGroup: "adults",
    category: "tops",
    priceUsd: 52,
    sizes: ["S", "M", "L", "XL"],
    colors: ["white", "ocean", "ember"],
    productDescription: "Breathable pique polo with a clean two-button placket.",
    inventory: 26,
  },
  {
    id: "card-018",
    name: "Aurora Knit Cardigan",
    ageGroup: "adults",
    category: "tops",
    priceUsd: 86,
    sizes: ["S", "M", "L"],
    colors: ["sand", "slate"],
    productDescription: "Midweight knit cardigan with patch pockets and shawl collar.",
    inventory: 10,
  },
  {
    id: "coat-019",
    name: "Arbor Parka",
    ageGroup: "adults",
    category: "outerwear",
    priceUsd: 178,
    sizes: ["S", "M", "L", "XL"],
    colors: ["forest", "black"],
    productDescription: "Insulated parka with storm flap and removable hood.",
    inventory: 8,
  },
  {
    id: "wind-020",
    name: "Seabreeze Windbreaker",
    ageGroup: "kids",
    category: "outerwear",
    priceUsd: 64,
    sizes: ["XS", "S", "M", "L"],
    colors: ["mist", "navy"],
    productDescription: "Packable windbreaker with mesh lining and zip pockets.",
    inventory: 18,
  },
  {
    id: "denim-021",
    name: "Ridge Straight Denim",
    ageGroup: "adults",
    category: "bottoms",
    priceUsd: 78,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["indigo", "coal"],
    productDescription: "Straight-leg denim with stretch and a clean finish.",
    inventory: 21,
  },
  {
    id: "skirt-022",
    name: "Lagoon Twill Skirt",
    ageGroup: "kids",
    category: "bottoms",
    priceUsd: 32,
    sizes: ["XS", "S", "M", "L"],
    colors: ["coral", "sand"],
    productDescription: "A-line twill skirt with adjustable waist tabs.",
    inventory: 32,
  },
  {
    id: "tank-023",
    name: "Breeze Linen Tank",
    ageGroup: "adults",
    category: "tops",
    priceUsd: 36,
    sizes: ["XS", "S", "M", "L"],
    colors: ["ivory", "sage"],
    productDescription: "Linen blend tank with airy drape and clean seams.",
    inventory: 34,
  },
  {
    id: "slide-024",
    name: "Harbor Slide",
    ageGroup: "kids",
    category: "footwear",
    priceUsd: 42,
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["sunset", "navy"],
    productDescription: "Water-friendly slide with cushioned footbed.",
    inventory: 27,
  },
  {
    id: "lace-025",
    name: "Lumen Lace-Up Sneaker",
    ageGroup: "adults",
    category: "footwear",
    priceUsd: 118,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["bone", "graphite"],
    productDescription: "Minimal lace-up sneaker with padded collar and rubber sole.",
    inventory: 19,
  },
];